# PyTorch tutorials

Tensors are fundamental data structures for deep learning.

Indices required | Computer Science | Mathematics
--- | --- | ---
0 | number | scalar
1 | array | vector
2 | 2D array | matrix

any dimension greater than 2 called n-dimension tensor / nd-tensor. 3D array called, 3D-tensor, etc

In [25]:
import torch
import numpy as np

### Accessing tensors with indices

In [1]:
a = [1,2,3,4]

In [2]:
a[2]

3

In [3]:
dd = [[1,2,3],
     [4,5,6],
     [7,8,9]]

In [6]:
dd[0][1]

2

### Rank, Axes and Shape

Build up concept of tensors.
1. Rank of a tensor indicates # of dimensions present within a tensor. In short it tells how many indices are required to access the tensor.

2. Rank = # of axes in the tensor 

3. Shape of the tensor is determined by the shape of each axis. (#rows, #columns, #channels/depth)

In [8]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

In [9]:
a[0]

[1, 2, 3]

In [10]:
a[1]

[4, 5, 6]

In [11]:
a[2]

[7, 8, 9]

In [12]:
a[0][0]

1

In [13]:
a[1][0]

4

In [14]:
a[2][0]

7

In [16]:
dd = [[[111, 112, 113], [121, 122, 123]],
     [[211, 212, 213], [221, 222, 223]],
     [[311, 312, 313], [321, 322, 323]]]
dd

[[[111, 112, 113], [121, 122, 123]],
 [[211, 212, 213], [221, 222, 223]],
 [[311, 312, 313], [321, 322, 323]]]

In [17]:
t = torch.tensor(dd)
t

tensor([[[111, 112, 113],
         [121, 122, 123]],

        [[211, 212, 213],
         [221, 222, 223]],

        [[311, 312, 313],
         [321, 322, 323]]])

In [20]:
t.shape  # size and shape of tensor is the same

torch.Size([3, 2, 3])

In [19]:
type(t)

torch.Tensor

### Tensor Reshaping

Changes the shape but not the underlying data.

In [21]:
a = torch.tensor(a)
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
a.shape

torch.Size([3, 3])

In [23]:
a.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
a.reshape(1,9).shape

torch.Size([1, 9])

### CNN Tensors

Shape of CNN tensor typically has length of 4. i.e we have rank 4 tensor with 4 axis. last axis is where data values are located

a = [a0,a1,a2,a3]

image data usually represented as:
[# of data samples, # channels, height, width], hence a 4D-tensor.

1. First axis: total samples / batch size of samples.
2. Second axis: color channels or depth of image
3. Third axis: height / rows in an image
4. Fourth axis: width, columns in an image

As image passes through the network, its shape changes. That means, the number of channels will increase of decrease based on number of filters present in the layer, while the height and width will change too, based on the convolution operations being performed in each layer.


When the convolution operation is performed, the output of each convolutional layer are modified images. The number of these images corresponds directly to the number of filters present in these layers. These are called **Feature Maps**. These feature maps are created due to convolution between the input color channels and the convolution filters.

### PyTorch Tensors

Apart from Rank, Axes, and Shape which are the fundamental attributes for all the tensors for all the deep learning frameworks, the attributes which are specific to PyTorch tensors are datatype, device and layout.

In [27]:
t = torch.Tensor()
t  # we can create an empty tensor

tensor([])

In [28]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


PyTorch attributes are:

1. DataType: specifies type of data contained in a tensor. Each data has CPU and GPU datatype. Tensor operations between tensors must happen with tensors of the same datatype.

2. Device: indicates where the tensor computations will be performed. Whether CPU or GPU. 

3. Layout: strided (tells us way in which data is laid out in memory). It is the default layout and not usually changed.


Tensors contain data of a uniform type. Tensor computations depends on the type and device.

In [30]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.,2.,3.,4.])

In [31]:
t1.dtype

torch.int64

In [32]:
t2.dtype

torch.float32

In [34]:
t1 + t2   # will fail due to non compatible datatypes

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0