In [2]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

### Tensors


Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [3]:
from __future__ import print_function
import torch

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [4]:
x = torch.empty(5, 3)  # x is a matrix which holds values already present in the memory location where it was initialized
print(x)

tensor([[2.3607e-09, 2.1156e+23, 1.7174e-07],
        [2.1066e-07, 2.0890e+20, 1.3673e-05],
        [8.3191e+20, 5.3482e+22, 2.4287e-18],
        [1.9421e+31, 2.7491e+20, 6.1949e-04],
        [7.1856e+22, 4.3605e+27, 2.3329e-18]])


Construct a randomly initialized matrix:



In [5]:
x = torch.rand(5, 3)   # this will help us initialize a mantrix with random numbers
print(x)

tensor([[0.3076, 0.9077, 0.7695],
        [0.2198, 0.3946, 0.2462],
        [0.1841, 0.0726, 0.8344],
        [0.1577, 0.3609, 0.1130],
        [0.2629, 0.7493, 0.6970]])


Construct a matrix filled zeros and of dtype long:



In [6]:
x = torch.zeros(5, 3, dtype=torch.long) # a 5x3 matrix of just 0 values having datatype of long
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7935, -0.0838, -1.0687],
        [ 0.1833, -1.7465,  0.2667],
        [-0.6863, -1.5854,  1.2928],
        [-0.4096, -1.8363, -0.9636],
        [ 0.7517, -0.7959,  1.0284]])


Get its size:



In [9]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

### Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [10]:
y = torch.rand(5, 3)    # create a matrix of random numbers. then add it to x
print(x + y)

tensor([[ 0.9710,  0.8560, -0.2935],
        [ 0.1837, -1.1266,  1.1848],
        [-0.3889, -1.4384,  2.2391],
        [-0.1297, -1.7383, -0.0685],
        [ 1.5532, -0.5815,  1.4855]])


Addition: syntax 2



In [11]:
print(torch.add(x, y))    # adding x and y torch tensors

tensor([[ 0.9710,  0.8560, -0.2935],
        [ 0.1837, -1.1266,  1.1848],
        [-0.3889, -1.4384,  2.2391],
        [-0.1297, -1.7383, -0.0685],
        [ 1.5532, -0.5815,  1.4855]])


Addition: providing an output tensor as argument



In [17]:
result = torch.empty(5, 3)   # create an empty 5x3 torch tensor of type float32
torch.add(x, y, out=result)  # add two tensors and specify the output variable as well.
print(result)

tensor([[ 1.7646,  0.7722, -1.3622],
        [ 0.3670, -2.8731,  1.4515],
        [-1.0752, -3.0238,  3.5319],
        [-0.5393, -3.5746, -1.0321],
        [ 2.3050, -1.3774,  2.5140]])


Addition: in-place



In [13]:
# adds x to y
# here the values in y are added to x and then stored in y itself, hence called inplace addition. Notice that the 
# operation function has a _ following its name. All inplace operations will have _ after their name. 
y.add_(x)
print(y)

tensor([[ 0.9710,  0.8560, -0.2935],
        [ 0.1837, -1.1266,  1.1848],
        [-0.3889, -1.4384,  2.2391],
        [-0.1297, -1.7383, -0.0685],
        [ 1.5532, -0.5815,  1.4855]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [14]:
print(x[:, 1])   # access all the rows and 1st column of the torch tensor, essentially similar to numpy indexing

tensor([-0.0838, -1.7465, -1.5854, -1.8363, -0.7959])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [28]:
x = torch.randn(8, 8)
y = x.view(64)
z = x.view(2, -1)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([8, 8]) torch.Size([64]) torch.Size([2, 32])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2097])
-0.20967504382133484


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [25]:
import numpy as np
a = np.ones(5)  # a numpy array of ones
b = torch.from_numpy(a)   # convert numpy array to torch tensor
np.add(a, 1, out=a)   # add 1 to numpy array a and store it in a itself. Notice that the numpy array change also 
# changed the torch tensor internally. Inshort numpy array to torch tensor or vice versa are just aliases pointing to
# the same memory location.
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [24]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!